Certificados/Models/Comerciantes.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Certificados.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Comerciantes
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Comerciantes()
        {
            this.Certificados = new HashSet<Certificados>();
            this.Rectificaciones = new HashSet<Rectificaciones>();
        }
    
        public int Id { get; set; }
        public string Nombres { get; set; }
        public string Apellidos { get; set; }
        public string Cedula { get; set; }
        public int Capacitacion { get; set; }
        public int instituciones_id { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Certificados> Certificados { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Rectificaciones> Rectificaciones { get; set; }
        public virtual Institucion Institucion2 { get; set; }
    }
}

Certificados/Models/ViewModel/ComercianteViewModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace Certificados.Models.ViewModel
{
    public class ComercianteViewModel
    {
        public int Id { get; set; }
        public string Nombres { get; set; }
        public string Apellidos { get; set; }
        public string Cedula { get; set; }
        public int Capacitacion { get; set; }
        public string Institucion { get; set; }
        public string CertificadoGenerado { get; set; }
    }
}

Certificados/Controllers/ComerciantesController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web.Mvc;
using System.Security.Cryptography;
using System.Text;
using Certificados.Models;
using Certificados.LogHistorial;
using QRCoder;
using iText.Kernel.Pdf;
using iText.Layout;
using iText.Kernel.Geom;
using iText.Forms;
using iText.Forms.Fields;
using iText.IO.Image;
using System.IO;

namespace Certificados.Controllers
{
    //[Authorize]
    public class ComerciantesController : Controller
    {
        private readonly ComerciantesEntities dbContextComerciantes = new ComerciantesEntities();
        public Log log = new Log();

        public ComerciantesEntities DbContextComerciantes => dbContextComerciantes;

        // GET: Comerciantes
        public ActionResult Index()
        {
            return View("NuevaBusqueda");
        }

        public ActionResult NuevaBusqueda()
        {
            return View();
        }

        public ActionResult BuscarCertificado()
        {
            return View("NuevaBusqueda");
        }

        [HttpPost]
        public ActionResult BuscarCertificado(string cedulaString, string apellidosString)  // buscar Comerciante en BDD por 
        {
            try
            {
                // texto ingresada para búsqueda
                ViewBag.DataCedula = cedulaString;
                ViewBag.DataApellidos = apellidosString;
                ViewBag.CertificadoGenerado = false;
                ViewBag.RectificacionGenerado = false;
                ViewBag.RectificacionId = 0;

                // validación de extensión de cedulaString (10 caracteres)
                if (cedulaString.Length == 10 && !String.IsNullOrWhiteSpace(apellidosString))
                {
                    // remover espacios blancos al inicio y final del string
                    apellidosString = apellidosString.Trim();

                    // comprobar si tiene certificado generado
                    Comerciantes comercianteTemp = GetComercianteByCedulaApellidos(cedulaString, apellidosString);

                    if (comercianteTemp != null)
                    {
                        if (GetCertificadoByComerId(comercianteTemp.Id) != null)
                        {
                            ViewBag.CertificadoGenerado = true;
                        }
                        else
                        {
                            // comprobar si tiene rectificación generada
                            Rectificaciones rectTemp = GetRectificacionByComerId(comercianteTemp.Id);
                            if (rectTemp != null)
                            {
                                ViewBag.RectificacionGenerado = true;
                                ViewBag.RectificacionId = rectTemp.Id;
                            }
                        }

                        log.Info(new Log_Registros()
                        {
                            mensaje_log = RouteData.Values["action"] + " en " + RouteData.Values["controller"].ToString() + "Controller: " + "Coincidencia encontrada de comerciante",
                            usuario_log = "Externo con parámetros " + cedulaString + " y apellidos " + apellidosString
                        });
                        return View(comercianteTemp);
                    }
                    else
                    {
                        log.Info(new Log_Registros()
                        {
                            mensaje_log = RouteData.Values["action"] + " en " + RouteData.Values["controller"].ToString() + "Controller: " + "No existen coincidencias de comerciante",
                            usuario_log = "Externo con parámetros " + cedulaString + " y apellidos " + apellidosString
                        });
                        return View("NoResultado");
                    }
                }
                else
                {
                    log.Warning(new Log_Registros()
                    {
                        mensaje_log = RouteData.Values["action"] + " en " + RouteData.Values["controller"].ToString() + "Controller: " + "Ingresa cédula con menos de 10 caracteres",
                        usuario_log = "Externo con parámetros " + cedulaString + " y apellidos " + apellidosString
                    });
                    return View("NoResultado");
                }
            }
            catch (Exception ex)
            {
                log.Error(new Log_Registros()
                {
                    mensaje_log = RouteData.Values["action"] + " en " + RouteData.Values["controller"].ToString() + "Controller: " + "Error al buscar de comerciante",
                    usuario_log = "Externo con parámetros " + cedulaString + " y apellidos " + apellidosString,
                    excepcion_log = ex.Message.ToString() + " - " + ex.StackTrace.ToString()
                });
                return View("NuevaBusqueda");
            }
        }


        public ActionResult GenerarCC(Comerciantes comerciante)    // generar Certificado PDF para descargar
        {
            try
            {
                Models.Certificados certTemp = GetCertificadoByComerId(comerciante.Id);
                comerciante = GetComercianteById(comerciante.Id);
                string pathDestinoDocumento = Server.MapPath("~/Documentos/CC/");

                // verificar si ya generó el documento para recuperarlo, caso contrario se registra
                if (certTemp != null)
                {
                    // si se ha generado, abrir documento y enviar para descarga
                    byte[] fileBytes = System.IO.File.ReadAllBytes(pathDestinoDocumento + certTemp.ruta_archivo);
                    return File(fileBytes, "application/pdf", certTemp.ruta_archivo);
                }
                else
                {
                    // verificar que exista una plantilla cargada para generar el CC
                    PlantillasCC plantillaCC = GetArchivoPlantillaCCActiva();
                    if (plantillaCC != null)
                    {
                        // DOCUMENTO: generar pdf y registrar objeto
                        // plantilla certificado path
                        string pathArchivoPlantilla = "~/PlantillasCC/";
                        string nombreArchivoPlantilla = plantillaCC.archivo_plantilla;

                        // si no se ha generado, crear el documento, registrar y enviar para descarga
                        certTemp = new Models.Certificados()
                        {
                            fecha_emision = DateTime.Now,
                            num_certificado = GetNumeroCertificado(),
                            comerciantes_id = comerciante.Id,
                            codigo_verificacion = CreateHashString(comerciante.Cedula),
                            ruta_archivo = comerciante.Apellidos.Trim().Replace(" ", "_") + "_" + DateTime.Now.GetHashCode().ToString().Replace("-", "") + ".pdf",
                            certificado_valido = true,
                            plantillascc_id = plantillaCC.Id
                        };

                        if (!String.IsNullOrWhiteSpace(nombreArchivoPlantilla))
                        {
                            // abrir plantilla
                            var pdfReader = new PdfReader(Request.MapPath(pathArchivoPlantilla + nombreArchivoPlantilla));

                            // buffer para almacenar
                            MemoryStream ms = new MemoryStream();
                            PdfWriter pw = new PdfWriter(ms);
                            PdfDocument pdf = new PdfDocument(pdfReader, pw);
                            Document doc = new Document(pdf, PageSize.A4);

                            // mapeo de datos - campos obligatorios
                            PdfAcroForm form = PdfAcroForm.GetAcroForm(pdf, true);
                            IDictionary<String, PdfFormField> fields = form.GetFormFields();

                            fields.TryGetValue("numero_doc", out PdfFormField toSet);
                            toSet.SetValue(GetNumBaseCertificado() + DateTime.Today.Year + "-" + certTemp.num_certificado);
                            fields.TryGetValue("fecha_doc", out toSet);
                            toSet.SetValue(certTemp.fecha_emision.ToLongDateString());
                            fields.TryGetValue("nombres_apellidos", out toSet);
                            toSet.SetValue(comerciante.Nombres.ToString().ToUpper() + " " + comerciante.Apellidos.ToString().ToUpper());
                            fields.TryGetValue("cedula", out toSet);
                            toSet.SetValue(comerciante.Cedula);
                            fields.TryGetValue("capacitacion", out toSet);
                            toSet.SetValue(comerciante.Capacitacion.ToString());
                            fields.TryGetValue("anio_cc", out toSet);
                            toSet.SetValue(certTemp.fecha_emision.Year.ToString());
                            fields.TryGetValue("institucion", out toSet);
                            toSet.SetValue(comerciante.Institucion2.nombre_institucion);
                            fields.TryGetValue("directorDCA", out toSet);
                            toSet.SetValue(GetDirectorDCA());
                            form.FlattenFields();

                            // generar y agregar código QR
                            ImageData imageData = ImageDataFactory.CreatePng(GenerarQRByte(comerciante.Nombres.Trim().Replace(" ", "_") + comerciante.Cedula));
                            iText.Layout.Element.Image image = new iText.Layout.Element.Image(imageData);
                            var pageWidth = pdf.GetDefaultPageSize().GetWidth();
                            var pageHeight = pdf.GetDefaultPageSize().GetHeight();
                            image.SetHeight(140f);
                            image.SetWidth(140f);

Certificados/Views/Comerciantes/BuscarCertificado.cshtml
@model Certificados.Models.Comerciantes

@{
    ViewBag.Title = "CERTIFICADOS: Resultado de la búsqueda";
    Layout = "~/Views/Shared/_Layout TB.cshtml";
    var rectificacionId = ViewBag.RectificacionId;
}

<div class="container">
    <div class="row col-md-offset-1 col-md-10">
        <h1 class="centrado">@ViewBag.Title</h1>
        <br />
        <h2>DATOS: <b>"@ViewBag.DataCedula"</b> y <b>"@ViewBag.DataApellidos"</b></h2>
        <br />
        <div>
            <div>
                @if (@ViewBag.CertificadoGenerado)
                {
                    <p>
                        Con los datos consultados ya se ha generado un certificado de capacitación, presione el botón
                        <b>Descargar certificado</b> para guardarlo.
                    </p>
                }
                else
                {
                    if (@ViewBag.RectificacionGenerado)
                    {
                        <p>
                            Con los datos consultados ya registra una solicitud de rectificación, presionar el botón
                            <b>Descargar solicitud</b>. para guardarlo. Recuerde que debe imprimir y firmar la solicitud para presentarla
                            en las oficinas de la ACDC.
                        </p>
                    }
                    else
                    {
                        <p>
                            Para obtener su certificado de capacitación, presione el botón <strong>"Generar documento"</strong>.
                            Si considera que sus datos contienen errores y deben solicitar su rectificación. Presione
                            <span>@Html.ActionLink("aquí", "RectificarDatos", "Comerciantes", Model, new { @class = "link-primary" })</span>.
                        </p>
                        <p>
                            <strong>Importante:</strong> Revise minuciosamente sus datos ya que una vez generado el certificado
                            de capacitación, NO podrá generar la solicitud la rectificación a través de este sistema.
                        </p>
                    }
                }

                <hr />
                <dl class="dl-horizontal">
                    <dt>
                        @Html.DisplayNameFor(model => model.Nombres)
                    </dt>
                    <dd>
                        @Html.DisplayFor(model => model.Nombres)
                    </dd>
                    <dt>
                        @Html.DisplayNameFor(model => model.Apellidos)
                    </dt>
                    <dd>
                        @Html.DisplayFor(model => model.Apellidos)
                    </dd>
                    <dt>
                        Cédula:
                        @*@Html.DisplayNameFor(model => model.Cedula)*@
                    </dt>
                    <dd>
                        @Html.DisplayFor(model => model.Cedula)
                    </dd>
                    <dt>
                        Año de capacitación:
                        @*@Html.DisplayNameFor(model => model.Capacitacion)*@
                    </dt>
                    <dd>
                        @Html.DisplayFor(model => model.Capacitacion)
                    </dd>
                    <dt>
                        Institución:
                        @*@Html.DisplayNameFor(model => model.InstitucionesDMQ.nombre_institucion)*@
                    </dt>
                    <dd>
                        @Html.DisplayFor(model => model.Institucion2.nombre_institucion)
                    </dd>
                </dl>
                <hr />
            </div>
        </div>
        <div>
            <p>
                @Html.ActionLink("Nueva Búsqueda", "NuevaBusqueda", "Comerciantes", null, htmlAttributes: new { @class = "btn btn-primary" })
                @if (@ViewBag.CertificadoGenerado)
                {
                    @Html.ActionLink("Descargar certificado", "GenerarCC", "Comerciantes", Model, new { @class = "btn btn-success" })
                }
                else
                {
                    if (@ViewBag.RectificacionGenerado)
                    {
                        @Html.ActionLink("Descargar solicitud", "DescargarRect", "Comerciantes", new { rectificacionId = rectificacionId } , htmlAttributes: new { @class = "btn btn-success" })
                    }
                    else
                    {
                        @Html.ActionLink("Generar documento", "GenerarCC", "Comerciantes", Model, new { @class = "btn btn-success" })
                    }
                }
            </p>
        </div>
    </div>
    <div class="col-md-1"></div>
</div>

Certificados/Views/Comerciantes/GenerarCC.cshtml
@model Certificados.Models.Certificados

@{
    ViewBag.Title = "CERTIFICADOS: Descargar documento";
}

<div class="container">
    <div class="row col-md-offset-1 col-md-11">
        <h1 class="centrado">@ViewBag.Title</h1>
        <br />

        <h4>Documento generado con éxito.</h4>

        <p>
            Se ha generado correctamente el certificado de capacitación para el/la señor(a)
            <strong>@Model.Comerciantes.Nombres @Model.Comerciantes.Apellidos</strong>, que puede descargarlo presionando
            <strong>@Html.ActionLink("aquí", "DescargarCC", "Comerciantes", new { certificadoId = @Model.Id }, new { @target = "_blank" })</strong>.
        </p>
        <br />

        <p>
            @Html.ActionLink("Regresar al inicio", "Index", "Home", null, htmlAttributes: new { @class = "btn btn-primary" })
            @Html.ActionLink("Nueva Búsqueda", "NuevaBusqueda", "Comerciantes", null, htmlAttributes: new { @class = "btn btn-success" })
        </p>
    </div>
    <div class="col-md-1"></div>
</div>

Certificados/Views/Comerciantes/GenerarRectificacion.cshtml
@model Certificados.Models.Rectificaciones

@{ 
    ViewBag.Title = "RECTIFICACIÓN: Descargar documento";
}

<div class="container">
    <div class="row col-md-offset-1 col-md-10">
        <h1 class="centrado">@ViewBag.Title</h1>
        <br />

        <h4>Documento generado con éxito.</h4>

        <p>
            Se ha generado correctamente la solicitud de rectificación de datos para el/la señor(a)
            <strong>@Model.Comerciantes.Nombres @Model.Comerciantes.Apellidos</strong>, que puede descargarlo presionando
            <strong>@Html.ActionLink("aquí", "DescargarRect", "Comerciantes", new { rectificacionId = @Model.Id }, new { @target = "_blank" })</strong>.
        </p>
        <br />

        <p>
            @Html.ActionLink("Regresar al inicio", "Index", "Home", null, htmlAttributes: new { @class = "btn btn-primary" })
            @Html.ActionLink("Nueva Búsqueda", "NuevaBusqueda", "Comerciantes", null, htmlAttributes: new { @class = "btn btn-success" })
        </p>
    </div>
    <div class="col-md-1"></div>
</div>

Certificados/Views/Comerciantes/NoResultado.cshtml
@model Certificados.Models.Comerciantes

@{
    ViewBag.Title = "CERTIFICADOS: Sin Resultados";
    Layout = "~/Views/Shared/_Layout TB.cshtml";
}

<div class="container">
    <div class="row col-md-offset-1 col-md-10">
        <h1 class="centrado">@ViewBag.Title</h1>
        <br />

        <div>
            <p>
                No se ha encontrado algún registro que coincida con la cédula de ciudadanía No. <strong>"@ViewBag.DataCedula"</strong>
                y los apellidos <strong>"@ViewBag.DataApellidos"</strong>.
            </p>
            <p>
                Revise que los datos ingresados estén correctos y vuelva a intentarlo presionando <strong>"Nueva Búsqueda"</strong>.
            </p>
        </div>
        <hr />

        <div>
            <p>
                @Html.ActionLink("Regresar al inicio", "Index", "Home", null, htmlAttributes: new { @class = "btn btn-primary" })
                @Html.ActionLink("Nueva Búsqueda", "NuevaBusqueda", "Comerciantes", null, htmlAttributes: new { @class = "btn btn-success" })
            </p>
        </div>
    </div>
    <div class="col-md-1"></div>
</div>

Certificados/Views/Comerciantes/NoValidacion.cshtml
@model Certificados.Models.Certificados

@{
    Layout = "~/Views/Shared/_Layout TB.cshtml";
    ViewBag.Title = "Validación de Certificado de Capacitación de Comerciante Autónomo".ToUpper();
}

<div class="container">
    <div class="row col-md-offset-1 col-md-10">
        <h1 class="centrado">@ViewBag.Title</h1>
        <br />
        
        <p>
            @ViewBag.Mensaje
        </p>        
    </div>
    <div class="col-md-1"></div>
</div>

Certificados/Views/Comerciantes/NuevaBusqueda.cshtml
@{
    ViewBag.Title = "CERTIFICADO DE CAPACITACIÓN: Búsqueda";
    Layout = "~/Views/Shared/_Layout TB.cshtml";
}

<div class="row">
    <div class="col-md-offset-1 col-md-10">
        <h1 class="centrado">@ViewBag.Title</h1>
        <br />
        <p>
            Para generar el certificado de capacitación, sus datos deben estar en los registros de la ACDC. Si desea realizar la búsqueda,
            ingrese los diez (10) dígitos de su número de identificación y sus apellidos.
        </p>
        <br />

        @using (Html.BeginForm("BuscarCertificado", "Comerciantes", FormMethod.Post, new { @class = "form-horizontal", role = "form" }))
        {
            @Html.AntiForgeryToken()
            @Html.ValidationSummary("", new { @class = "text-danger" })

            <div class="form-group">
                @Html.Label("Cédula:", htmlAttributes: new { @class = "control-label col-md-2", @for = "cedulaString" })
                <div class="col-md-10">
                    @Html.Editor("cedulaString", new { htmlAttributes = new { @class = "form-control", @minlength = "10", @maxlength = "10", @title = "Ingrese los 10 dígitos de la cédula", @onKeypress = "if (event.keyCode < 48 || event.keyCode > 57) event.returnValue = false;", @onCopy = "return false", @onDrag = "return false", @onDrop = "return false", @onPaste = "return false", @autocomplete = "off", @required = "required" } })
                </div>
            </div>
            <div class="form-group">
                @Html.Label("Apellidos:", htmlAttributes: new { @class = "control-label col-md-2", @for = "apellidosString" })
                <div class="col-md-10">
                    @Html.Editor("apellidosString", new { htmlAttributes = new { @class = "form-control", @minlength = "1", @maxlength = "50", @title = "Ingrese los apellidos completos", @onkeypress = "return soloLetras(event)", @onCopy = "return false", @onDrag = "return false", @onDrop = "return false", @onPaste = "return false", @autocomplete = "off", @required = "required" } })
                </div>
            </div>
            <br />
            <div class="form-group">
                <div class="col-md-2"></div>
                <div class="col-md-10">
                    @Html.ActionLink("Regresar", "Index", "Home", null, htmlAttributes: new { @class = "btn btn-primary" })
                    <input type="submit" class="btn btn-success" value="Buscar &raquo;" />
                </div>
            </div>
        }
    </div>
    <div class="col-md-1"></div>
</div>

<script>
    function soloLetras(e) {
        key = e.keyCode || e.which;
        tecla = String.fromCharCode(key).toLowerCase();
        letras = " áéíóúabcdefghijklmnñopqrstuvwxyz";
        especiales = [8, 37, 39, 46];

        tecla_especial = false
        for (var i in especiales) {
            if (key == especiales[i]) {
                tecla_especial = true;
                break;
            }
        }

        if (letras.indexOf(tecla) == -1 && !tecla_especial)
            return false;
    }
</script>

Certificados/Views/Comerciantes/ProblemaGenerar.cshtml
@model Certificados.Models.Comerciantes

@{
    ViewBag.Title = "ERROR: Al generar el documento";
    Layout = "~/Views/Shared/_Layout TB.cshtml";
}

<div class="container">
    <div class="row col-md-offset-1 col-md-offset-10">
        <h1 class="centrado">@ViewBag.Title</h1>
        <br />

        <div>
            <h4>Lo sentimos...</h4>
        </div>

        <div>
            <p>
                @ViewBag.Mensaje
            </p>
        </div>
        <br />

        <div>
            <p>
                @Html.ActionLink("Regresar al inicio", "Index", "Home", null, htmlAttributes: new { @class = "btn btn-primary" })
                @Html.ActionLink("Nueva Búsqueda", "NuevaBusqueda", "Comerciantes", null, htmlAttributes: new { @class = "btn btn-success" })
            </p>
        </div>

    </div>
    <div class="col-md-1"></div>
</div>

Certificados/Views/Comerciantes/RectificarDatos.cshtml
@model Certificados.Models.ComerciantesRectificacionesView

@{
    Layout = "~/Views/Shared/_Layout TB.cshtml";
    ViewBag.Title = "Rectificación de datos".ToUpper();
    var dataInstitucionesDMQ = (List<SelectListItem>)ViewData["institucionesDMQ"];
}

<div class="container">
    <div class="row col-md-offset-1 col-md-10">
        <h1 class="centrado">@ViewBag.Title</h1>
        <br />

        <p>
            Si considera que sus datos están incorrectos, puede solicitar su rectificación mediante oficio dirigido la Agencia de
            Coordinación Distrital del Comercio - ACDC. En esta página, usted pude generar automáticamente este documento, marcando
            las casillas que corresponden a los campos a rectificar. Se recomienda revisar sus datos, ya que una vez generada la
            solicitud, no podrá emitir el certificado de capacitación hasta que su requerimiento sea atendido por la ACDC.
        </p>

        <div>
            <hr />
            <dl class="dl-horizontal">
                <dt>
                    Nombres y Apellidos:
                </dt>
                <dd>
                    @Model.Nombres @Model.Apellidos
                </dd>
                <dt>
                    No. Identidicación:
                </dt>
                <dd>
                    @Model.Cedula
                </dd>
                <dt>
                    Institución Actual:
                </dt>
                <dd>
                    @Model.nombre_institucion
                </dd>
            </dl>
            <hr />
        </div>

        @if (!String.IsNullOrWhiteSpace(ViewBag.Mensaje))
        {
            <p class="text-danger">
                <strong>NOTA:</strong> @ViewBag.Mensaje
            </p>
        }

        <p>
            Para continuar, marque las casillas a rectificar o el cambio de institución:
        </p>

        <div class="row">
            <div class="col-md-12">
                @using (Html.BeginForm("GenerarRectificacion", "Comerciantes", FormMethod.Post, htmlAttributes: new { @class = "form-horizontal", @role = "form", @onsubmit = "return validateForm();" }))
                {
                    @Html.AntiForgeryToken()

                    <div class="form-group">
                        <div class="col-md-offset-1 col-md-11">
                            @Html.CheckBoxFor(m => m.rectificar_nom_ape)
                            @Html.LabelFor(m => m.rectificar_nom_ape, "Nombres y/o apellidos")
                        </div>
                        <div class="col-md-offset-1 col-md-11">
                            @Html.CheckBoxFor(m => m.rectificar_cedula)
                            @Html.LabelFor(m => m.rectificar_cedula, "Cédula")
                        </div>
                    </div>

                    <div class="form-group">
                        <div class="col-md-12">
                            <fieldset>
                                <legend>
                                    Si desea cambiar de institución, seleccione otra opción:
                                </legend>
                                @*<div class="col-md-offset-1 col-md-11">
                                    <input id="labelInput" type="checkbox" value = "@dataInstitucionesDMQ[0].Value" />
                                    <label for="labelInput">@dataInstitucionesDMQ[0].Text</label>
                                </div>*@

                                @foreach (var item in dataInstitucionesDMQ)
                                {
                                    if (item.Text != @Model.nombre_institucion)
                                    {
                                        <div class="col-md-offset-1 col-md-11">
                                            @Html.RadioButtonFor(m => m.rectificar_inst_destino, item.Value, htmlAttributes: new { @aria_labelledby = item.Value })
                                            @Html.LabelFor(m => m.rectificar_inst_destino, item.Text)
                                        </div>
                                    }
                                }
                            </fieldset>
                            @Html.HiddenFor(m => m.comer_id)
                            @Html.HiddenFor(m => m.rectificar_inst_origen)
                        </div>
                    </div>
                    <hr />

                    <div class="form-group">
                        <p>
                            Presione <strong>"Generar oficio"</strong> para descargar el documento. Imprimímalo, firmelo y entréguelo en
                            la dirección calle Jorge Washington E4-54 y Av. Amazonas, Edificio Secretaría de Salud, primer piso.
                        </p>
                        <br />

                        <div class="col-md-offset-1 col-md-11">
                            @Html.ActionLink("Cancelar", "NuevaBusqueda", "Comerciantes", null, htmlAttributes: new { @class = "btn btn-danger" })
                            <input type="submit" class="btn btn-success" value="Generar oficio" />
                        </div>
                    </div>
                }
            </div>
        </div>
    </div>
    <div class="col-md-1"></div>
</div>

@section scripts{
    <script type="text/javascript">
        function validateForm() {
            var nombresApellidos = document.getElementById('rectificar_nom_ape').checked;
            var cedula = document.getElementById('rectificar_cedula').checked;
            var tempDestino = document.getElementById('rectificar_inst_destino');
            var valueDestino = tempDestino.options[tempDestino.checked].value;
            if (!nombresApellidos && !cedula && valueDestino == 0) {
                alert("Para generar su solicitud, debe marcar al menos una casilla o cambiar de institución.");
                return false;
            }
            else {
                alert(nombresApellidos + " ; " + cedula + " ; " + valueDestino);
                return false;
            }
        }
    </script>
}