Certificados/Models/Documentos.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Certificados.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Documentos
    {
        public int Id { get; set; }
        public System.DateTime fecha_generado { get; set; }
        public int dato_id { get; set; }
        public string ruta_archivo { get; set; }
        public string codigo_verificacion { get; set; }
        public bool valido { get; set; }
    
        public virtual Datos Datos { get; set; }
    }
}

Certificados/Models/ViewModel/DocumentoViewModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace Certificados.Models.ViewModel
{
    public class DocumentoViewModel
    {
        public string Nombres_Apellidos { get; set; }
        public string Curso_Taller { get; set; }
        public string Fecha_Curso_Taller { get; set; }
        public string Fecha { get; set; }
        public string Archivo { get; set; }
        public string Codigo_Verificacion { get; set; }
    }
}

Certificados/Controllers/DocumentosController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web.Mvc;
using Certificados.Models;
using System.IO;
using System.IO.Compression;
using Certificados.Models.ViewModel;
using Certificados.LogHistorial;

namespace Certificados.Controllers
{
    [Authorize]
    public class DocumentosController : Controller
    {
        private readonly ComerciantesEntities dbContextPlantilla = new ComerciantesEntities();
        public Log log = new Log();

        public ComerciantesEntities DbContextPlantilla => dbContextPlantilla;

        // GET: Documentos
        public ActionResult Index()
        {
            return View("IndexDocumentos");
        }

        public ActionResult IndexDocumentos()
        {
            return View();
        }

        public JsonResult ListarDocumentos()
        {
            List<DocumentoViewModel> listaResultado = new List<DocumentoViewModel>();
            using (ComerciantesEntities db = new ComerciantesEntities())
            {
                listaResultado = (from doc in db.Documentos
                                  join dato in db.Datos on doc.dato_id equals dato.Id
                                  select new DocumentoViewModel
                                  {
                                      Nombres_Apellidos = dato.nombres_apellidos,
                                      Curso_Taller = dato.curso_taller,
                                      Fecha_Curso_Taller = dato.fecha,
                                      Fecha = doc.fecha_generado.ToString(),
                                      Archivo = doc.ruta_archivo,
                                      Codigo_Verificacion = doc.codigo_verificacion
                                  }
                                  ).ToList();
            }
            return Json(new { data = listaResultado }, JsonRequestBehavior.AllowGet);
        }

        public ActionResult VerDocumento(string rutaArchivo)
        {
            try
            {
                string pathDescarga = Server.MapPath("~/Documentos/OtrosDocumentos/");
                if (System.IO.File.Exists(pathDescarga + rutaArchivo))
                {
                    byte[] fileBytes = System.IO.File.ReadAllBytes(pathDescarga + rutaArchivo);
                    log.Error(new Log_Registros()
                    {
                        mensaje_log = RouteData.Values["action"] + " en " + RouteData.Values["controller"].ToString() + "Controller: " + "Descarga de archivo Documentos: " + pathDescarga + rutaArchivo,
                        usuario_log = User.Identity.Name
                    });

                    return File(fileBytes, "application/pdf", rutaArchivo);
                }
                else
                {
                    throw new FileNotFoundException();
                }
            }
            catch (FileNotFoundException exFNF)
            {
                log.Error(new Log_Registros()
                {
                    mensaje_log = RouteData.Values["action"] + " en " + RouteData.Values["controller"].ToString() + "Controller: " + "No se encuentra el archivo Documentos: " + rutaArchivo,
                    usuario_log = User.Identity.Name,
                    excepcion_log = exFNF.Message.ToString() + " - " + exFNF.StackTrace.ToString()
                });
                ViewBag.Mensaje = "No se ha encontrado el archivo indicado.";
                //ViewBag.MensajeError = "Error: " + fileNotFoundException.Message.ToString();
                return View("ReporteError");
            }
            catch (Exception ex)
            {
                log.Error(new Log_Registros()
                {
                    mensaje_log = RouteData.Values["action"] + " en " + RouteData.Values["controller"].ToString() + "Controller: " + "Error al cargar intentar descargar archivo Documentos: " + rutaArchivo,
                    usuario_log = User.Identity.Name,
                    excepcion_log = ex.Message.ToString() + " - " + ex.StackTrace.ToString()
                });
                ViewBag.Mensaje = "Se ha presentado un problema al intentar descargar el documento.";
                //ViewBag.MensajeError = "Error: " + ex.Message.ToString();
                return View("ReporteError");
            }
        }

        public ActionResult DetallarDocumento(int idDoc)
        {
            try
            {
                Documentos docDetalles = GetDocumentoById(idDoc);
                if (docDetalles != null)
                {
                    log.Info(new Log_Registros()
                    {
                        mensaje_log = RouteData.Values["action"] + " en " + RouteData.Values["controller"].ToString() + "Controller: " + "Se recupera detalles de Documento con id=" + idDoc,
                        usuario_log = User.Identity.Name
                    });
                    return View(docDetalles);
                }
                else
                {
                    log.Warning(new Log_Registros()
                    {
                        mensaje_log = RouteData.Values["action"] + " en " + RouteData.Values["controller"].ToString() + "Controller: " + "No se ha encontrado Documento con id=" + idDoc,
                        usuario_log = User.Identity.Name
                    });
                    ViewBag.Mensaje = "No se encuentran detalles de este documento.";
                    ViewBag.MensajeError = "Por favor, intente más tarde";
                    return View("ReporteError");
                }
            }
            catch (Exception ex)
            {
                log.Error(new Log_Registros()
                {
                    mensaje_log = RouteData.Values["action"] + " en " + RouteData.Values["controller"].ToString() + "Controller: " + "Error al detallar documento",
                    usuario_log = User.Identity.Name,
                    excepcion_log = ex.Message.ToString() + " - " + ex.StackTrace.ToString()
                });
                return View("ReporteError");
            }
        }

        // no se utiliza
        public JsonResult Descargar(string[] docsIdArray)   // prueba ResultJson a AJAX para descarga
        {
            string listaString = String.Empty;
            foreach (var docId in docsIdArray)
            {
                listaString = listaString + docId + ",";
            }
            return Json(data: new { lista = listaString });
        }

        // no se utiliza
        public ActionResult DescargarZipDocumentos(string[] docsIdArray)    // descarga ZIP de documentos generados
        {
            try
            {
                if (docsIdArray != null || docsIdArray.Length > 0)
                {
                    // obtener lista de documentos generados
                    List<Documentos> listaDocumentos = new List<Documentos>();
                    foreach (var item in docsIdArray)
                    {
                        if (Int32.TryParse(item, out int datoId))
                        {
                            listaDocumentos.Add(GetDocumentoById(datoId));
                        }
                    }

                    // creación del archivo ZIP
                    string pathDescarga = Server.MapPath("~/Documentos/OtrosDocumentos/");
                    using (var ms = new MemoryStream())
                    {
                        using (var archivo = new ZipArchive(ms, ZipArchiveMode.Create, true))
                        {
                            foreach (Documentos doc in listaDocumentos)
                            {
                                var entry = archivo.CreateEntry(doc.ruta_archivo);
                                using (var entryStream = entry.Open())
                                using (var fileStream = System.IO.File.OpenRead(pathDescarga + doc.ruta_archivo))
                                {
                                    fileStream.CopyTo(entryStream);
                                }
                            }
                        }
                        return File(ms.ToArray(), "application/zip", "documentos.zip");
                    };
                }
                else
                {
                    ViewBag.Mensaje = "Debe seleccionar al menos un documento para iniciar la descarga.";
                    return RedirectToAction("ListarDocumentos");
                }
            }
            catch (Exception ex)
            {
                ViewBag.Mensaje = "No se ha podido atender su requerimiento debido a un error del sistema.";
                ViewBag.MensajeError = "Por favor, intente más tarde." + "Error: " + ex.Message.ToString();
                return View("ReporteError");
            }
        }

        // métodos de soporte --------------------------------------

        public List<Documentos> GetDocumentos()
        {
            var result = from d in dbContextPlantilla.Documentos
                         select d;
            return result.Any() ? result.ToList() : null;
        }

        public Documentos GetDocumentoById(int idDoc)
        {
            var result = from d in dbContextPlantilla.Documentos
                         where d.Id == idDoc
                         select d;
            return result.Any() ? result.First() : null;
        }
    }
}

Certificados/Views/Documentos/DetallarDocumento.cshtml
@model Certificados.Models.Documentos

@{
    ViewBag.Title = "DOCUMENTO: Detalles";
}

<style type="text/css">
    h2 {
        text-align: center;
    }
</style>

<div>
    <h2>@ViewBag.Title</h2>
    <br />

    <div>
        <p>
            El documento seleccionado contiene los siguientes datos.
        </p>
        <ul>
            <li><b>NOMBRES Y APELLIDOS:</b> @Model.Datos.nombres_apellidos</li>
            <li><b>CURSO / TALLER:</b> @Model.Datos.curso_taller</li>
            <li><b>FECHA:</b> @Model.Datos.fecha</li>
            <li><b>CREACIÓN:</b> @Model.Datos.fecha_registro.ToString("dd/MM/yyyy")</li>
            <li><b>ARCHIVO:</b> @Html.ActionLink(Model.ruta_archivo, "VerDocumento", "Documentos", new { rutaArchivo = Model.ruta_archivo }, htmlAttributes: new { @target = "_blank" })</li>
            <li><b>CÓDIGO DE VERIFICACIÓN:</b> @Model.codigo_verificacion</li>
            @if (Model.Datos.opcional1 != "0")
            {
                <li><b>CAMPO OPCIONAL 1:</b> @Model.Datos.opcional1</li>
            }
            @if (Model.Datos.opcional2 != "0")
            {
                <li><b>CAMPO OPCIONAL 2:</b> @Model.Datos.opcional2</li>
            }
            @if (Model.Datos.opcional3 != "0")
            {
                <li><b>CAMPO OPCIONAL 3:</b> @Model.Datos.opcional3</li>
            }
            @if (Model.Datos.opcional4 != "0")
            {
                <li><b>CAMPO OPCIONAL 4:</b> @Model.Datos.opcional4</li>
            }
        </ul>
    </div><br />

    <div class="col-md-12">
        <p>
            @Html.ActionLink("Regresar", "ListarDocumentos", "Documentos", Model, htmlAttributes: new { @class = "btn btn-primary" })
        </p>
    </div><br />
</div>

Certificados/Views/Documentos/IndexDocumentos.cshtml
@{
    ViewBag.Title = "DOCUMENTOS GENERADOS";
    Layout = "~/Views/Shared/_Layout TB.cshtml";
}

<style type="text/css">
    h2, th, td {
        text-align: center !important;
    }
</style>

<div class="container">
    <h2>@ViewBag.Title</h2>
    <br />
    <p>
        @Html.ActionLink("Regresar", "AdministrarPlantillas", "Plantilla", null, htmlAttributes: new { @class = "btn btn-primary" })
    </p>

    <div class="row">
        <div class="col-sm-12">
            <div class="panel panel-primary">
                <div class="panel panel-heading">COMERCIANTES AUTÓNOMOS CAPACITADOS DEL DMQ</div>
                <div class="panel panel-body">
                    <table id="tbComerciantes" class="table">
                        <thead>
                            <tr>
                                <th>Nombres y Apellidos</th>
                                <th>Curso / Taller</th>
                                <th>Fecha Curso / Taller</th>
                                <th>Generado</th>
                                <th>Archivo</th>
                                <th>Código de verificación</th>
                            </tr>
                        </thead>
                    </table>
                </div>
            </div>
        </div>
    </div>
</div>

@section scripts{
    <script>

        var tabla_comerciantes;
        $(document).ready(function () {
            tabla_comerciantes = $('#tbComerciantes').DataTable({
                "ajax": {
                    "url": "@Url.Action("ListarDocumentos", "Documentos")",
                    "type": "GET",
                    "dataType": "json"
                },
                "columns": [
                    { "data": "Nombres_Apellidos" },
                    { "data": "Curso_Taller" },
                    { "data": "Fecha_Curso_Taller" },
                    { "data": "Fecha" },
                    { "data": "Archivo", "render": function (data) {
                        return "<a href='VerDocumento/?rutaArchivo=" + data + "' target='_blank'>Descargar</a>";
                        }
                    },
                    { "data": "Codigo_Verificacion" }
                ],
            });
        });

    </script>
}

Certificados/Views/Documentos/ListarDocumentosNO.cshtml
@model IEnumerable<Certificados.Models.Documentos>

@{
    ViewBag.Title = "DOCUMENTOS GENERADOS";
}

<style type="text/css">
    h2, th, td {
        text-align: center;
    }
</style>

<div>
    <h2>@ViewBag.Title</h2>
    <br />
    <p>
        @Html.ActionLink("Regresar", "AdministrarPlantillas", "Plantilla", null, htmlAttributes: new { @class = "btn btn-primary" })
    </p>

    @if (Model != null)
    {
        if (String.IsNullOrEmpty(ViewBag.Mensaje))
        {
            @ViewBag.Mensaje
            <br />
        }

        <table class="table">
            <tr>
                <th>
                    Fecha de creación
                </th>
                <th>
                    Archivo
                </th>
                <th>
                    Código de verificación
                </th>
                <th>Opciones</th>
            </tr>

            @foreach (var item in Model)
            {
                <tr>
                    <td>
                        @item.fecha_generado.ToString("dd/MM/yyyy")
                    </td>
                    <td>
                        @Html.ActionLink(item.ruta_archivo, "VerDocumento", "Documentos", new { rutaArchivo = item.ruta_archivo }, htmlAttributes: new { @target = "_blank" })
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.codigo_verificacion)
                    </td>
                    <td>
                        @Html.ActionLink("Ver detalles", "DetallarDocumento", "Documentos", new { idDoc = item.Id }, htmlAttributes: new { name = "detalles" })
                    </td>
                </tr>
            }
        </table>
        <hr />
    }
    else
    {
        <p>Por el momento, no existen documentos generados para mostrar.</p>
        <br />
    }
</div>

@section scripts{
    <script type="text/javascript">



        @*$(document).ready(function () {
            $('#descargar').click(function () {
                var idCheckedValues = [];
                $(".docGenerado:checked").each(function () {
                    idCheckedValues.push($(this).val());
                });

                if (idCheckedValues.length > 0) {
                    var param = {
                        'docsIdArray': idCheckedValues
                    };

                    $.ajax({
                        url: '@Url.Action("Descargar", "Documentos")',
                        data: JSON.stringify(param),
                        type: "POST",
                        dataType: "json",
                        contentType: 'application/json; charset=utf-8',
                        success: function (data) {
                            alert("success1");
                            window.location = '/Documentos/DescargarZipDocumentos/' + data.lista;
                            alert("success2");
                        },
                        error: function (data) {
                            alert("Error" + data.responseText);
                        }
                    });
                } else {
                    alert("Para iniciar la descarga, debe seleccionar al menos una casilla.");
                    return false;
                }

            })
        });*@
    </script>
}

Certificados/Views/Documentos/ReporteError.cshtml
@model Certificados.Models.Documentos

@{
    ViewBag.Title = "DOCUMENTOS: Reporte de error";
}

<style type="text/css">
    h2 {
        text-align: center;
    }
</style>

<div>
    <h2>@ViewBag.Title</h2>
    <br />
    <h4>
        Mensaje:
    </h4>
    <p>
        @ViewBag.Mensaje
    </p>
    <p>
        @ViewBag.MensajeError
    </p>
    <p>
        <a href="~/Plantilla/AdministrarPlantillas" class="btn btn-danger">Regresar</a>
    </p>
</div>