Certificados/Controllers/RegistrosController.cs
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Text;
using System.Web;
using System.Web.Mvc;
using Certificados.Models;
using Certificados.Models.ViewModel;
using Certificados.LogHistorial;

namespace Certificados.Controllers
{
    [Authorize(Roles = "Admin")]
    public class RegistrosController : Controller
    {
        private readonly ComerciantesEntities dbContextRegistros = new ComerciantesEntities();
        public Log log = new Log();
        
        public ComerciantesEntities DbContextRegistros => dbContextRegistros;

        // GET: Registros - ADMIN
        public ActionResult Index()
        {
            //return View(GetComerciantesList());

            List<InstitucionViewModel> inst = null;
            using (ComerciantesEntities db = new ComerciantesEntities())
            {
                inst = (from d in db.Institucion
                        select new InstitucionViewModel
                        {
                            Id = d.Id,
                            Nombre = d.nombre_institucion
                        }).ToList();
            }

            List<SelectListItem> items = inst.ConvertAll(d =>
            {

                return new SelectListItem()
                {
                    Text = d.Nombre.ToString(),
                    Value = d.Id.ToString(),
                };

            });

            ViewBag.items = items;
            return View();
        }


        public ActionResult SubirArchivo()
        {
            ViewBag.Observaciones = false;
            return View();
        }
        

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult CargarDatosDCA(HttpPostedFileBase file)
        {
            // para mensajes de validación
            ViewBag.Mensaje = String.Empty;
            ViewBag.Observaciones = false;

            // instanciación de variables iniciales
            List<string> listaObservacionesCSV = new List<string>();
            List<Comerciantes> registrosGuardados = new List<Comerciantes>();
            try
            {
                // verifica que se haya subido un archivo y no está vacío
                if (file != null && file.ContentLength > 0)
                {
                    // verificar que sea archivo .CSV
                    String fileExt = Path.GetExtension(file.FileName).ToUpper();
                    if (fileExt == ".CSV")
                    {
                        // guardar archivo CSV - temporal
                        string nombreArchivoCSV = Path.GetFileName(file.FileName).Trim().Replace(" ", "_");
                        string pathArchivoCSV = Path.Combine(Server.MapPath("~/Temporal/"), nombreArchivoCSV);
                        file.SaveAs(pathArchivoCSV);

                        // lectura de datos del archivo CSV
                        List<Comerciantes> listaComerciantesRegistrar = new List<Comerciantes>();
                        string csvDataTexto = System.IO.File.ReadAllText(pathArchivoCSV, Encoding.UTF8).Trim();

                        // verifica que el archivo no esté vacío
                        if (!String.IsNullOrWhiteSpace(csvDataTexto))
                        {
                            string[] csvDataArray = csvDataTexto.Replace("\r", "").Split('\n');

                            // si último elemento de array está vacío, lo elimina
                            if (String.IsNullOrWhiteSpace(csvDataArray.Last()))
                            {
                                csvDataArray = csvDataArray.Take(csvDataArray.Count() - 1).ToArray();
                            }

                            // recorre array pasando la primera fila que contiene los headers
                            for (int i = 1; i < csvDataArray.Length; i++)
                            {
                                // verifica que la fila no esté vacía
                                if (!String.IsNullOrWhiteSpace(csvDataArray[i]))
                                {
                                    string[] csvDataFila = csvDataArray[i].Split(',');
                                    List<string> listaObservacionesFila = VerificarRegistroComeriantes(csvDataFila);

                                    // verifica si hay observaciones que impidan guardar el registro
                                    if (listaObservacionesFila.Count() == 0)
                                    {
                                        listaComerciantesRegistrar.Add(new Comerciantes()
                                        {
                                            Nombres = csvDataFila[0].Trim().ToUpper(),
                                            Apellidos = csvDataFila[1].Trim().ToUpper(),
                                            Cedula = csvDataFila[2].Trim(),
                                            Capacitacion = ConvertirInt(csvDataFila[3].Trim()),
                                            instituciones_id = ConvertirInt(csvDataFila[4].Trim())
                                        });
                                    }
                                    else
                                    {
                                        listaObservacionesCSV.Add("Fila " + (i + 1).ToString() + ": " + String.Join("; ", listaObservacionesFila));
                                    }
                                }
                                else
                                {
                                    listaObservacionesCSV.Add("Fila " + (i + 1).ToString() + " está vacía.");
                                }
                            }
                        }
                        else
                        {
                            log.Info(new Log_Registros()
                            {
                                mensaje_log = RouteData.Values["action"] + " en " + RouteData.Values["controller"].ToString() + "Controller: " + "Sube archivo vacío",
                                usuario_log = User.Identity.Name
                            });

                            ViewBag.Mensaje = "El archivo " + nombreArchivoCSV + " está vacío.";
                            return View("SubirArchivo");
                        }

                        // eliminar archivo CVS cargado
                        EliminarArchivoTemporal(pathArchivoCSV);

                        // verificar que la lista a registrar no esté vacía
                        if (listaComerciantesRegistrar.Count != 0)
                        {
                            // verificar cédulas repetidas en lista a guardar
                            List<string> listaCedulasRepetidas = BuscarCedulasRepetidas(listaComerciantesRegistrar);
                            if (listaCedulasRepetidas.Count() > 0)
                            {
                                foreach (var item in listaCedulasRepetidas)
                                {
                                    listaObservacionesCSV.Add("El valor del campo CEDULA '" + item + "' está repetido en los registros a cargar.");
                                }
                            }

                            if (listaObservacionesCSV.Count() == 0 && listaComerciantesRegistrar.Count > 0)
                            {
                                // guardar en tabla COMERCIANTES
                                foreach (Comerciantes comer in listaComerciantesRegistrar)
                                {
                                    dbContextRegistros.Comerciantes.Add(comer);
                                    dbContextRegistros.SaveChanges();
                                    registrosGuardados.Add(GetComercianteById(comer.Id));
                                }

                                // guardar el log
                                log.Transaction(new Log_Registros()
                                {
                                    mensaje_log = RouteData.Values["action"] + " en " + RouteData.Values["controller"].ToString() + "Controller: " + "Carga exitosa de registros en base de datos",
                                    usuario_log = User.Identity.Name
                                });
                                // respuesta a Vista
                                ViewBag.CantidadRegistros = registrosGuardados.Count();
                                return View();
                            }
                            else if (listaObservacionesCSV.Count() == 0 && listaComerciantesRegistrar.Count == 0)
                            {
                                log.Info(new Log_Registros()
                                {
                                    mensaje_log = RouteData.Values["action"] + " en " + RouteData.Values["controller"].ToString() + "Controller: " + "Sube archivo vacío",
                                    usuario_log = User.Identity.Name
                                });
                                ViewBag.Mensaje = "El archivo cargado está vacío.";
                                ViewData["listaObservaciones"] = listaObservacionesCSV;
                                return View("SubirArchivo");
                            }
                            else
                            {
                                log.Info(new Log_Registros()
                                {
                                    mensaje_log = RouteData.Values["action"] + " en " + RouteData.Values["controller"].ToString() + "Controller: " + "Sube archivo con errores",
                                    usuario_log = User.Identity.Name
                                });
                                ViewBag.Observaciones = true;
                                ViewBag.Mensaje = "No se puede cargar el archivo porque contiene los siguientes errores.";
                                ViewData["listaObservaciones"] = listaObservacionesCSV;

Certificados/Views/Registros/CargarDatosDCA.cshtml
@{
    ViewBag.Title = "REGISTROS: Comerciantes";
}

<div class="container">
    <div class="row col-md-offset-1 col-md-10">
        <h1 class="centrado">@ViewBag.Title</h1>
        <br />

        <h2>Carga de registros exitosa</h2>
        <br />

        <p>
            Se ha(n) registrado <strong>@ViewBag.CantidadRegistros</strong> comerciante(s) en la base de datos. Las personas registradas podrán generar sus
            certificados en el sistema de forma automática.
        </p>
        <br />

        <p>
            @Html.ActionLink("Regresar", "Index", "Tecnico", null, htmlAttributes: new { @class = "btn btn-success" })
        </p>
    </div>
    <div class="col-md-1"></div>
</div>

Certificados/Views/Registros/Index.cshtml
@{
    ViewBag.Title = "REGISTROS: Comerciantes";
    List<SelectListItem> items = (List<SelectListItem>)ViewBag.items;
    Layout = "~/Views/Shared/_Layout TB.cshtml";
}

<style type="text/css">
    th, td {
        text-align: center !important;
    }
</style>

<div class="container">
    <div class="row col-md-offset-1 col-md-10">
        <h1 class="centrado">@ViewBag.Title</h1>
        <br />

        @if (Request.IsAuthenticated && User.IsInRole("Admin"))
        {
            <p>
                @Html.ActionLink("Cargar Registros", "SubirArchivo", "Registros", null, htmlAttributes: new { @class = "btn btn-success" })
            </p>
        }

        <div class="row">
            <div class="col-sm-12">
                <div class="panel panel-primary">
                    <div class="panel panel-heading">LISTADO DE COMERCIANTES AUTÓNOMOS CAPACITADOS DEL DMQ</div>
                    <div class="panel panel-body">
                        <table id="tbComerciantes" class="table">
                            <thead>
                                <tr>
                                    <th>Cédula</th>
                                    <th>Nombres</th>
                                    <th>Apellidos</th>
                                    <th>Institución</th>
                                    <th>Certificado Generado</th>
                                    <th>Edición</th>
                                </tr>
                            </thead>
                        </table>
                    </div>
                </div>
            </div>
        </div>
        <div class="row">
            <p><strong>NOTA: </strong>El enlace de descarga permite bajar un archivo en formato PDF.</p>
        </div>
    </div>    
</div>


<!-- Modal -->
<div class="modal fade" id="FormModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h2 class="modal-title" id="exampleModalLabel"><b>Editar datos del comerciante</b></h2>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
            <div class="modal-body">
                <div class="row">
                    <div class="col-sm-12">

                        <div class="form-group" hidden>
                            <label for="txtIdPersona">Id</label>
                            <input type="text" id="txtIdPersona" />
                        </div>

                        <div class="form-group">
                            <label for="txtCedula">Cédula:</label>
                            <input type="text" class="form-control" id="txtCedula" min="10" maxlength="10" onKeypress="if (event.keyCode < 48 || event.keyCode > 57) event.returnValue = false;" onCopy="return false;" onDrag="return false;" onDrop="return false;" onPaste="return false;" autocomplete="off">
                        </div>
                        <div class="form-group">
                            <label for="txtNombres">Nombres:</label>
                            <input type="text" class="form-control" id="txtNombres" min="1" , maxlength="50" onkeypress="return soloLetras(event);" onCopy="return false;" onDrag="return false;" onDrop="return false;" onPaste="return false;" autocomplete="off">
                        </div>
                        <div class="form-group">
                            <label for="txtApellidos">Apellidos:</label>
                            <input type="text" class="form-control" id="txtApellidos" min="1" , maxlength="50" onkeypress="return soloLetras(event);" onCopy="return false;" onDrag="return false;" onDrop="return false;" onPaste="return false;" autocomplete="off">
                        </div>
                        <div class="form-group">
                            <label for="txtCapacitacion">Capacitación:</label>
                            <input type="text" class="form-control" id="txtCapacitacion" min="4" maxlength="4" onKeypress="if (event.keyCode < 48 || event.keyCode > 57) event.returnValue = false;" onCopy="return false;" onDrag="return false;" onDrop="return false;" onPaste="return false;" autocomplete="off">
                        </div>

                        <div class="form-group">
                            <label for="txtInstitucionId">Institución:</label>
                            @Html.DropDownList("txtInstitucionId", items, new { @class = "form-control" })
                        </div>
                    </div>
                </div>

            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-danger" data-dismiss="modal">Cancelar</button>
                <button type="button" class="btn btn-success" onclick="ConfirmarGuardar();">Guardar</button>
            </div>
        </div>
    </div>
</div>



@section scripts{
    <script>

        var tabla_comerciantes;
        $(document).ready(function () {
            tabla_comerciantes = $('#tbComerciantes').DataTable({
                "ajax": {
                    "url": "@Url.Action("ListarComerciantes", "Tecnico")",
                    "type": "GET",
                    "dataType": "json"
                },
                "columns": [
                    { "data": "Cedula" },
                    { "data": "Nombres" },
                    { "data": "Apellidos" },
                    { "data": "Institucion" },
                    { "data": "CertificadoGenerado", render: function (data) {
                            if (data != "NO") {
                                return "<a href='/Tecnico/VerCC/?rutaArchivo=" + data + "' target='_blank'>Descargar</a>";
                            } else {
                                return data;
                            }
                        }
                    },
                    { "data": "Id", "render": function (data) {
                        return "<button class='btn btn-primary btn-sm' type='button' onclick='abrirModal(" + data + ")'><i class='fas fa-pen'></i> Editar</button>"
                        },
                        "orderable": false,
                        "searchable": false,
                        "width": "150px"
                    }
                ],
            });
        });

        function abrirModal($ID) {
            $("#txtIdPersona").val($ID);
            if ($ID != 0) {
                jQuery.ajax({
                    url: "@Url.Action("ObtenerComerciante", "Tecnico")" + "?ID=" + $ID,
                    type: "GET",
                    dataType: "json",
                    contentType: "application/json; charset=utf-8",
                    success: function (data) {
                        if (data != null) {
                            $("#txtIdPersona").val($ID);
                            $("#txtCedula").val(data.Cedula);
                            $("#txtNombres").val(data.Nombres);
                            $("#txtApellidos").val(data.Apellidos);
                            $("#txtCapacitacion").val(data.Capacitacion);
                            $("#txtInstitucionId").val(data.instituciones_id);
                        }
                    }
                });
            }
            $('#FormModal').modal('show');
        }

        function soloLetras(e) {
            key = e.keyCode || e.which;
            tecla = String.fromCharCode(key).toLowerCase();
            letras = " áéíóúabcdefghijklmnñopqrstuvwxyz";
            especiales = [8, 37, 39, 46];

            tecla_especial = false
            for (var i in especiales) {
                if (key == especiales[i]) {
                    tecla_especial = true;
                    break;
                }
            }

            if (letras.indexOf(tecla) == -1 && !tecla_especial)
                return false;
        }

        function ConfirmarGuardar() {
            var respuesta = confirm("¿Está seguro de guardar los cambios?");
            if (respuesta) {
                Guardar();
            } else {
                return;
            }
        }

        function Guardar() {
            var $data = {
                oComerciante: {
                    ID: parseInt($("#txtIdPersona").val()),
                    Cedula: parseInt($("#txtCedula").val()),
                    Nombres: $("#txtNombres").val(),
                    Apellidos: $("#txtApellidos").val(),
                    Capacitacion: parseInt($("#txtCapacitacion").val()),
                    Instituciones_id: parseInt($("#txtInstitucionId").val())
                }
            }

            jQuery.ajax({
                url: "/Tecnico/Guardar",
                type: "POST",
                data: JSON.stringify($data),
                dataType: "json",
                contentType: "application/json; charset=utf-8",
                success: function (data) {

                    if (data.resultado) {
                        tabla_comerciantes.ajax.reload();
                        $('#FormModal').modal('hide');
                        alert(data.message);
                    } else {
                        alert(data.message);
                    }
                },
                error: function (error) {
                    console.log(error)
                },
                beforeSend: function () {

                }
            });
        }
        
    </script>
}

Certificados/Views/Registros/SubirArchivo.cshtml
@{
    ViewBag.Title = "REGISTROS: Cargar datos de comerciantes";
    var listaObservacionesCSV = (List<string>)ViewData["listaObservaciones"];
}

<div class="container">
    <div class="row col-md-offset-1 col-md-10">
        <div>
            <h1 class="centrado">@ViewBag.Title</h1>
            <br />

            <p>
                En esta página, usted puede cargar los registros de los comerciantes que han sido aprobado el curso de capacitación y pueden generar
                su certificado en este aplicativo. Para hacerlo, deberá utilizar el formato específico en un archivo CSV.
            </p>
            <p>
                Para continuar seleccione el archivo CSV y presione el botón <strong>"Subir archivo"</strong>.
            </p>

            @if (!String.IsNullOrEmpty(ViewBag.Mensaje))
            {
                <div class="text-danger">
                    <p>
                        <strong>NOTA:</strong> @ViewBag.Mensaje
                    </p>
                </div>
            }

            @if (ViewBag.Observaciones)
            {
                <div>
                    <hr />
                    <h5>Observaciones:</h5>
                    <ul>
                        @foreach (var item in listaObservacionesCSV)
                        {
                            <li>@item</li>
                        }
                    </ul>
                    <hr />
                </div>
            }
            <br />

            @using (@Html.BeginForm("CargarDatosDCA", "Registros", FormMethod.Post, new { enctype = "multipart/form-data" }))
            {
                @Html.AntiForgeryToken()

                <div class="form-horizontal">
                    @Html.ValidationSummary(true, "", new { @class = "text-danger" })

                    <div class="form-group">
                        <div>
                            @Html.Label("file", "Archivo:", htmlAttributes: new { @class= "col-md-offset-1 col-md-1" })
                        </div>
                        <div class="col-md-10">
                            @Html.TextBox("file", "", new { type = "file", accept = ".csv", required = "required" })
                            @Html.ValidationMessage("file", "*Debe seleccionar un archivo CSV.", new { @class = "text-danger" })
                        </div>
                    </div><br />
                    <div class="form-group">
                        <div class="col-md-offset-1 col-md-11">
                            @Html.ActionLink("Cancelar", "Index", "Registros", null, htmlAttributes: new { @class = "btn btn-danger" })
                            <input type="submit" value="Subir archivo" class="btn btn-success" />
                        </div>
                    </div>
                </div>
            }
        </div>
    </div>
    <div class="col-md-1"></div>
</div>    

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}