Certificados/Controllers/RolesAdminController.cs
using IdentitySample.Models;
using Microsoft.AspNet.Identity;
using Microsoft.AspNet.Identity.Owin;
using Microsoft.AspNet.Identity.EntityFramework;
using System.Linq;
using System.Net;
using System.Threading.Tasks;
using System.Web;
using System.Web.Mvc;
using System.Collections.Generic;

namespace IdentitySample.Controllers
{
    [Authorize(Roles = "Admin")]
    public class RolesAdminController : Controller
    {
        public RolesAdminController()
        {
        }

        public RolesAdminController(ApplicationUserManager userManager,
            ApplicationRoleManager roleManager)
        {
            UserManager = userManager;
            RoleManager = roleManager;
        }

        private ApplicationUserManager _userManager;
        public ApplicationUserManager UserManager
        {
            get
            {
                return _userManager ?? HttpContext.GetOwinContext().GetUserManager<ApplicationUserManager>();
            }
            set
            {
                _userManager = value;
            }
        }

        private ApplicationRoleManager _roleManager;
        public ApplicationRoleManager RoleManager
        {
            get
            {
                return _roleManager ?? HttpContext.GetOwinContext().Get<ApplicationRoleManager>();
            }
            private set
            {
                _roleManager = value;
            }
        }

        //
        // GET: /Roles/
        [HttpGet]
        public ActionResult Index()
        {
            return View(RoleManager.Roles);
        }

        //
        // GET: /Roles/Details/5
        [HttpGet]
        public async Task<ActionResult> Details(string id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            var role = await RoleManager.FindByIdAsync(id);
            // Get the list of Users in this Role
            var users = new List<ApplicationUser>();

            // Get the list of Users in this Role
            foreach (var user in UserManager.Users.ToList())
            {
                if (await UserManager.IsInRoleAsync(user.Id, role.Name))
                {
                    users.Add(user);
                }
            }

            ViewBag.Users = users;
            ViewBag.UserCount = users.Count();
            return View(role);
        }

        //
        // GET: /Roles/Create
        [HttpGet]
        public ActionResult Create()
        {
            return View();
        }

        //
        // POST: /Roles/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Create(RoleViewModel roleViewModel)
        {
            if (ModelState.IsValid)
            {
                var role = new IdentityRole(roleViewModel.Name);
                var roleresult = await RoleManager.CreateAsync(role);
                if (!roleresult.Succeeded)
                {
                    ModelState.AddModelError("", roleresult.Errors.First());
                    return View();
                }
                return RedirectToAction("Index");
            }
            return View();
        }

        //
        // GET: /Roles/Edit/Admin
        [HttpGet]
        public async Task<ActionResult> Edit(string id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            var role = await RoleManager.FindByIdAsync(id);
            if (role == null)
            {
                return HttpNotFound();
            }
            RoleViewModel roleModel = new RoleViewModel { Id = role.Id, Name = role.Name };
            return View(roleModel);
        }

        //
        // POST: /Roles/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Edit([Bind(Include = "Name,Id")] RoleViewModel roleModel)
        {
            if (ModelState.IsValid)
            {
                var role = await RoleManager.FindByIdAsync(roleModel.Id);
                role.Name = roleModel.Name;
                await RoleManager.UpdateAsync(role);
                return RedirectToAction("Index");
            }
            return View();
        }

        //
        // GET: /Roles/Delete/5
        [HttpGet]
        public async Task<ActionResult> Delete(string id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            var role = await RoleManager.FindByIdAsync(id);
            if (role == null)
            {
                return HttpNotFound();
            }
            return View(role);
        }

        //
        // POST: /Roles/Delete/5
        [HttpPost]
        [ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> DeleteConfirmed(string id, string deleteUser)
        {
            if (ModelState.IsValid)
            {
                if (id == null)
                {
                    return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
                }
                var role = await RoleManager.FindByIdAsync(id);
                if (role == null)
                {
                    return HttpNotFound();
                }
                IdentityResult result;
                if (deleteUser != null)
                {
                    result = await RoleManager.DeleteAsync(role);
                }
                else
                {
                    result = await RoleManager.DeleteAsync(role);
                }
                if (!result.Succeeded)
                {
                    ModelState.AddModelError("", result.Errors.First());
                    return View();
                }
                return RedirectToAction("Index");
            }
            return View();
        }
    }
}

Certificados/Views/RolesAdmin/Create.cshtml
@model IdentitySample.Models.RoleViewModel

@{
    ViewBag.Title = "ROLES: Crear";
}

<div class="container">
    <div class="row col-md-offset-1 col-md-10">
        <h1 class="centrado">@ViewBag.Title</h1>
        <br />

        @using (Html.BeginForm())
        {
            @Html.AntiForgeryToken()

            <div class="form-horizontal">

                <hr />
                @*@Html.ValidationSummary(true)*@

                <div class="form-group">
                    @Html.LabelFor(model => model.Name, new { @class = "control-label col-md-2" })
                    <div class="col-md-10">
                        @Html.TextBoxFor(model => model.Name, new { @class = "form-control", @maxlength = "50", @onkeypress = "return soloLetras(event);", @onCopy = "return false;", @onDrag = "return false;", @onDrop = "return false;", @onPaste = "return false;", @autocomplete = "off", @required = "required" })
                        @Html.ValidationMessageFor(model => model.Name, "Campo requerido")
                    </div>
                </div>

                <div class="form-group">
                    <div class="col-md-offset-2 col-md-10">
                        @Html.ActionLink("Cancelar", "Index", "RolesAdmin", null, htmlAttributes: new { @class = "btn btn-danger" })
                        <input type="submit" class="btn btn-success" value="Crear Rol" />
                    </div>
                </div>
            </div>
        }

    </div>
    <div class="col-md-1"></div>
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval");
    <script type="text/javascript">
        function soloLetras(e) {
            key = e.keyCode || e.which;
            tecla = String.fromCharCode(key).toLowerCase();
            letras = " áéíóúabcdefghijklmnñopqrstuvwxyz";
            especiales = [8, 37, 39, 46];

            tecla_especial = false
            for (var i in especiales) {
                if (key == especiales[i]) {
                    tecla_especial = true;
                    break;
                }
            }

            if (letras.indexOf(tecla) == -1 && !tecla_especial)
                return false;
        }
    </script>
}

Certificados/Views/RolesAdmin/Delete.cshtml
@model Microsoft.AspNet.Identity.EntityFramework.IdentityRole

@{
    ViewBag.Title = "ROLES: Eliminar";
}

<style type="text/css">
    h2 {
        text-align: center;
    }
</style>

<div class="container">
    <div class="row col-md-offset-1 col-md-10">
        <h1 class="centrado">@ViewBag.Title</h1>
        <br />

        <p>¿Está seguro de que desea eliminar el rol <strong>"@Model.Name"</strong>?</p>
        <p>Eliminar el rol quitará a todos los usuarios de este rol pero el usuario permanecerá activo.</p>
        <br />

        <div>

            <!--<hr />
            <dl class="dl-horizontal">
                <dt>-->
                    @*@Html.DisplayNameFor(model => model.Name)*@
                    <!--Rol:
                </dt>
                <dd>
                    @Html.DisplayFor(model => model.Name)
                </dd>
            </dl>-->

            @using (Html.BeginForm())
            {
                @Html.AntiForgeryToken()

                <div class="form-actions no-color">
                    @Html.ActionLink("Regresar", "Index", "RolesAdmin", null, htmlAttributes: new { @class = "btn btn-primary" })
                    <input type="submit" value="Eliminar" class="btn btn-danger" />
                </div>
            }
        </div>

    </div>
    <div class="col-md-1"></div>
</div>

Certificados/Views/RolesAdmin/Details.cshtml
@model Microsoft.AspNet.Identity.EntityFramework.IdentityRole

@{
    ViewBag.Title = "ROLES: Detalle";
}

<div class="container">
    <div class="row col-md-offset-1 col-md-10">
        <h1 class="centrado">@ViewBag.Title</h1>
        <br />

        <div>
            <hr />
            <dl class="dl-horizontal">
                <dt>
                    @*@Html.DisplayNameFor(model => model.Name)*@
                    Rol:
                </dt>
                <dd>
                    @Html.DisplayFor(model => model.Name)
                </dd>
            </dl>
        </div>

        <p>Lista de usuarios con este rol</p>
        @if (ViewBag.UserCount == 0)
        {
            <hr />
            <p>No existen usuarios en este rol.</p>
        } else { 
            <ul>
                @foreach (var item in ViewBag.Users)
                {
                    <li>@item.UserName</li>
                }
            </ul>
        }
        <br />  
        
        <p>
            @Html.ActionLink("Regresar", "Index", "RolesAdmin", null, htmlAttributes: new { @class = "btn btn-danger" })
            @Html.ActionLink("Editar rol", "Edit", "RolesAdmin", new { id = Model.Id }, htmlAttributes: new { @class = "btn btn-success" })
        </p>
    </div>
    <div class="col-md-1"></div>
</div>

Certificados/Views/RolesAdmin/Edit.cshtml
@model IdentitySample.Models.RoleViewModel

@{
    ViewBag.Title = "ROLES: Edición";
}

<div class="container">
    <div class="row col-md-offset-1 col-md-10">
        <h1 class="centrado">@ViewBag.Title</h1>
        <br />

        @using (Html.BeginForm())
        {
            @Html.AntiForgeryToken()

            <div class="form-horizontal">

                <hr />
                @*@Html.ValidationSummary(true)*@
                @Html.HiddenFor(model => model.Id)

                <div class="form-group">
                    @Html.LabelFor(model => model.Name, new { @class = "control-label col-md-2" })
                    <div class="col-md-10">
                        @Html.TextBoxFor(model => model.Name, new { @class = "form-control", @maxlength = "50", @onkeypress = "return soloLetras(event);", @onCopy = "return false;", @onDrag = "return false;", @onDrop = "return false;", @onPaste = "return false;", @autocomplete = "off", @required = "required" })
                        @Html.ValidationMessageFor(model => model.Name, "Campo requerido")
                    </div>
                </div>

                <div class="form-group">
                    <div class="col-md-offset-2 col-md-10">
                        @Html.ActionLink("Cancelar", "Index", "RolesAdmin", null, htmlAttributes: new { @class = "btn btn-danger" })
                        <input type="submit" class="btn btn-success" value="Guardar Cambios" />
                    </div>
                </div>
            </div>
        }

    </div>
    <div class="col-md-1"></div>
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval");

    <script type="text/javascript">
        function soloLetras(e) {
            key = e.keyCode || e.which;
            tecla = String.fromCharCode(key).toLowerCase();
            letras = " áéíóúabcdefghijklmnñopqrstuvwxyz";
            especiales = [8, 37, 39, 46];

            tecla_especial = false
            for (var i in especiales) {
                if (key == especiales[i]) {
                    tecla_especial = true;
                    break;
                }
            }

            if (letras.indexOf(tecla) == -1 && !tecla_especial)
                return false;
        }
    </script>
}

Certificados/Views/RolesAdmin/Index.cshtml
@model IEnumerable<Microsoft.AspNet.Identity.EntityFramework.IdentityRole>

@{
    ViewBag.Title = "ADMINISTRACIÓN: Roles";
}

<div class="container">
    <div class="row col-md-offset-1 col-md-10">
        <h1 class="centrado">@ViewBag.Title</h1>
        <br />

        <p>
            @Html.ActionLink("Nuevo Rol", "Create")
        </p>
        <table class="table">
            <caption hidden>Administración de roles de usuario</caption>
            <tr>
                <th>
                    @*@Html.DisplayNameFor(model => model.Name)*@
                    Nombre del rol
                </th>
                <th>
                    Opciones
                </th>
            </tr>

            @foreach (var item in Model)
            {
                <tr>
                    <td>
                        @Html.DisplayFor(modelItem => item.Name)
                    </td>
                    <td>
                        @Html.ActionLink("Editar", "Edit", new { id = item.Id }) |
                        @Html.ActionLink("Detalles", "Details", new { id = item.Id }) |
                        @Html.ActionLink("Eliminar", "Delete", new { id = item.Id })
                    </td>
                </tr>
            }

        </table>
    </div>
    <div class="col-md-1"></div>
</div>